# This reusable workflow builds the project and tests it.

# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.

name: common

on:
  workflow_call:
    inputs:
      python-version:
        description: "A version of a python interpreter to use"
        default: "3.7"
        required: false
        type: string
      cmake-version:
        description: "CMake version to use"
        default: "3.24.x"
        required: false
        type: string

jobs:
  build-all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-22.04", "windows-latest"]

    steps:
      - name: Choose OS
        if: ${{ !startsWith(matrix.os, 'windows') }}
        uses: ./.github/workflows/common-ubuntu.yml
        with:
          python-version: "3.7"
          os: "ubuntu-22.04"
          cmake-version: "3.24.x"

      - name: Choose OS
        if: ${{ startsWith(matrix.os, 'windows') }}
        uses: ./.github/workflows/common-windows.yml
        with:
          python-version: "3.7"
          os: "windows-latest"
          cmake-version: "3.24.x"