# This reusable workflow builds the project and tests it.

# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.

name: common

on:
  workflow_call:
    inputs:
      python-version:
        description: "A version of a python interpreter to use"
        default: "3.7"
        required: false
        type: string
      os:
        description: "A container which is used to make a build"
        default: "ubuntu-22.04"
        required: false
        type: string
      cmake-version:
        description: "CMake version to use"
        default: "3.24.x"
        required: false
        type: string

jobs:
  build-all:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true

      - name: Build Rust library
        working-directory: ./lib
        run: |
          cargo check
          cargo build

      - name: Install cbindgen
        uses: actions-rs/cargo@v1.0.1
        with:
          command: install
          args: cbindgen

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{ inputs.cmake-version }}

      - name: Install Conan
        uses: turtlebrowser/get-conan@v1.2
        with:
          version: "2.5.0"

      - name: Setup Conan profile
        run: |
          conan profile detect --force
        shell: bash

      - name: Choose OS
        if: ${{ startsWith(inputs.os, 'windows') }}
        uses: './.github/workflows/common-windows'
        with:
          python-version: "3.7"
          os: "windows-latest"
          cmake-version: "3.24.x"

      - name: Choose OS
        if: ${{ !startsWith(inputs.os, 'windows') }}
        uses: './.github/workflows/common-unix'
        with:
          python-version: "3.7"
          os: "ubuntu-22.04"
          cmake-version: "3.24.x"